python train.py --gpus=3 \
 --train_data_dir ~/codes/datasets/TianChiBuilding/train \
 --name ResNeSt26dMeanGSoPSCA_2UnetPP \
 --model ResNeSt26dMeanGSoPSCA_2UnetPP \
 --precision 16 \
 --buildingSegTransform True \
 --batch_size 16 \
 --epochs 64 \
 --learning_rate 0.0008 \
 --optimizer adam \
 --kfold 2 \
 --img_size 512 \
