python train.py --gpus=3 \
 --train_data_dir ~/codes/datasets/TianChiBuilding/train \
 --name ResNeSt26dMeanGSoPSCA_2UnetPP \
 --model ResNeSt26dMeanGSoPSCA_2UnetPP \
 --precision 16 \
 --buildingSegTransform True \
 --batch_size 16 \
 --epochs 12 \
 --learning_rate 0.0016 \
 --optimizer adam \
 --kfold 5 \
 --img_size 512 \
 --gpus 2 \
 --use_swa True \
 --accumulate_grad_batches 2 \